### ISSUE TITLE
"RuntimeError: Error(s) in loading state_dict for KPFCNN:" when running test_models.py 

### ISSUE THREAD

**Issue by amiltonwong** [MehmetAygun/4D-PLS#1]
Hi, @MehmetAygun ,

Thanks for releasing the package. I got the following error when running `test_models.py`. I got the following error:

```
Model Preparation
*****************
Traceback (most recent call last):
  File "test_models.py", line 215, in <module>
    tester = ModelTester(net, chkp_path=chosen_chkp)
  File "/data/code13/4D-PLS/utils/tester.py", line 77, in __init__
    net.load_state_dict(checkpoint['model_state_dict'])
  File "/root2/anaconda3/envs/pytorch1.5_4d_pls/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for KPFCNN:
	size mismatch for head_softmax.mlp.weight: copying a param with shape torch.Size([19, 256]) from checkpoint, the shape in current model is torch.Size([25, 256]).
	size mismatch for head_softmax.batch_norm.bias: copying a param with shape torch.Size([19]) from checkpoint, the shape in current model is torch.Size([25]).
```

Here is the [link](https://gist.github.com/amiltonwong/ba26d30ec808d6099d39a0a240ef5bbd) for the log details.  Could you give some hints to solve this issue?

Thanks~

**Comment by amiltonwong** [comment]
Supplement:

Here is what I set in config.py:

```
    # Dataset name
    dataset = 'SemanticKitti'

    # Type of network model
    dataset_task = '4d_panoptic'
```

**Comment by MehmetAygun** [comment]
Hi, normally there should be 19 classes on the model output, that part of the model is created using the config file, can you check the mappings etc on the semantic-kitti.yaml file ?

**Comment by amiltonwong** [comment]
Hi, @MehmetAygun ,

Thanks for your reply. Here is the [semantic-kitti.yaml](https://gist.github.com/amiltonwong/d49e99a5201a40b38b026ff84e045820) I used. Is that correct?

Thanks~

**Comment by amiltonwong** [comment]
Hi, @MehmetAygun,

I found this error in my semantic-kitti.yaml. I download it again and the dimension mismatch error is solved. However, now I encountered the second error as follows:

```
(pytorch1.5_4d_pls) root@milton-ThinkCentre-M93p:/data/code13/4D-PLS# python test_models.py

Data Preparation
****************
Preparing seq 08 class frames. (Long but one time only)


Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"random_51.000_0.061_1_83629": 1
Check neighbors limit dictionary
"random_83629_0.061_0.152": 10
"random_83629_0.122_0.305": 20
"random_83629_0.244_0.610": 26
"random_83629_0.488_1.220": 29
"random_83629_0.976_2.440": 31
"random_83629_1.952_4.880": 32
Calibration done in 0.1s


Model Preparation
*****************
Model and training state restored.
Done in 145.3s


Start test
**********

Initialize workers
Done in 9.4s
Traceback (most recent call last):
  File "test_models.py", line 231, in <module>
    tester.panoptic_4d_test(net, test_loader, config)
  File "/data/code13/4D-PLS/utils/tester.py", line 840, in panoptic_4d_test
    self.next_ins_id, batch.points, batch.times.unsqueeze(1), pose)
  File "/data/code13/4D-PLS/models/architectures.py", line 633, in ins_pred_in_time
    bbox, kalman_bbox = get_bbox_from_points(points[0][ids])
  File "/data/code13/4D-PLS/models/architectures.py", line 87, in get_bbox_from_points
    return [x1,y1,z1,x2,y2,z2], np.array([x1 + (x2-x1)/2, y1+ (y2-y1)/2,z1+ (z2-z1)/2, 0, x2-x1,y2-y1,z2-z1]) # x, y, z, theta, l, w, h
  File "/root2/anaconda3/envs/pytorch1.5_4d_pls/lib/python3.7/site-packages/torch/tensor.py", line 492, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

```

Could you give some hints to fix this issue? 

Thanks~

**Comment by MehmetAygun** [comment]
it is related to part that not neccessary to use(I forget to delete that part), so you can change models/architectures.py line 633

change bbox, kalman_bbox = get_bbox_from_points(points[0][ids]) to bbox, kalman_bbox = None, None,

can you confirm if that works ?
